import Head from 'next/head'
import { Unbounded } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '@/components/Card/index'
import Link from 'next/link'

const unbounded = Unbounded({ subsets: ['latin'] })

export default function Home() {
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Wotakoi Digital Marketing Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div class="navbar">
          <div class="nav-title">Wotakoi Digital Marketing Agency</div>
          <div class="nav-button">
            <Link className={styles.link} href="about">Learn More on Them</Link>
          </div>
        </div>
        {
          information && information.map((info, index) => {
            if(info.department.toLowerCase() === "business"){
              return (<Card 
                  key={index} 
                  degree={info.degree} 
                  gpa={info.gpa}
                  colourInfo="#EB6314;" 
                  font="25px"
                  fontColour="#FFFF"
                />
              )
            }
          })
        }

        {
          information && information.map((info, index) => {
            if(info.department.toLowerCase() === "computing"){
              return (<Card
                  key={index} 
                  degree={info.degree} 
                  gpa={info.gpa}
                  font="25px"
                  fontColour="#FFFF"
                  colourInfo="#FF9BE4" 
                />
              )
            }
          })
        }
      </main>
    </>
  )
}
